# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjini', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_description',
            field=models.CharField(default='Contact us for business definition', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='business',
            name='business_number',
            field=models.IntegerField(default=0),
        ),
    ]
