# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjini', '0002_auto_20181019_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.AlterField(
            model_name='business',
            name='business_description',
            field=models.TextField(max_length=80),
        ),
    ]
