# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-19 13:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mjini', '0003_auto_20181019_0950'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('post', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='hoodpin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hood',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='post',
            name='hood',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hood', to='mjini.Hood'),
        ),
        migrations.AddField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to=settings.AUTH_USER_MODEL),
        ),
    ]
