# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mjini', '0005_profile_hood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hood',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='home', to='mjini.Hood'),
        ),
    ]
