# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mjini', '0008_auto_20181021_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hood',
            name='county',
        ),
        migrations.RemoveField(
            model_name='hood',
            name='residents',
        ),
    ]
