# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjini', '0009_auto_20181021_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='bio',
            field=models.CharField(default=models.CharField(max_length=20, unique=True), max_length=40),
        ),
    ]
