# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-21 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mjini', '0010_hood_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='bio',
            field=models.CharField(default='', max_length=40),
        ),
    ]
