# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 06:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mjini', '0012_auto_20181021_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='hood',
            name='admin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='administrate', to='mjini.Profile'),
            preserve_default=False,
        ),
    ]
