# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-22 06:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mjini', '0013_hood_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrate', to=settings.AUTH_USER_MODEL),
        ),
    ]
